apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpu-shim
  labels:
    chaincode: cpu-use 
spec:
  replicas: 3
  selector:
    matchLabels:
      chaincode: cpu-use
  template:
    metadata:
      labels:
        chaincode: cpu-use
    spec:
      containers:
      - name: cpu-shim
        image: gcr.io/ngp-intern-platform/cpu-shim-test:v1.2.0
        command: [ "cpu"]
        ports:
        - containerPort: 7053
        env:
          - name: CHAINCODE_SERVER_ADDRESS
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: CHAINCODE_ID
            value: cpu-use:f3834fc9eca6f91c288c559f31fd0e727da91b92dc30ee1d9f7a793426696a41